# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
mandelbrot <- function(z, itDepth = 500L) {
    .Call(`_viscomplexr_mandelbrot`, z, itDepth)
}

#' @export
juliaNormal <- function(z, c, R_esc, itDepth = 500L) {
    .Call(`_viscomplexr_juliaNormal`, z, c, R_esc, itDepth)
}

