# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mandel_1 <- function(z, itDepth = 52L) {
    .Call(`_viscomplexr_mandel_1`, z, itDepth)
}

mandel_2 <- function(z, itDepth = 52L) {
    .Call(`_viscomplexr_mandel_2`, z, itDepth)
}

mandel_3 <- function(z, itDepth = 52L) {
    .Call(`_viscomplexr_mandel_3`, z, itDepth)
}

