name: Codecov for viscomplexr
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
    - name: Setup R
      uses: actions/setup-r@master
    - name: Codecov
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1.0.15
      with:
        file: ./coverage.xml # optional
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
